### ISSUE TITLE
Compatibility with recent versions of tidyverse

### ISSUE THREAD

**Issue by grosenberger** [IFIproteomics/LFQbench#5]
It seems that LFQbench has some compatibility issues with recent versions of tidyverse. The example produces the following error:

```
folder ../ext/data/vignette_examples/hye124/supplementary does not exist, creating ... done!
Generating peptide report for ../ext/data/vignette_examples/hye124/PeakView_TTOF6600_64w_benchmark_example.xlsx
Adding missing grouping variables: `Peptide`, `Protein`
Error: invalid column index : NA for variable: 'Peptide' = 'Peptide'
```

It works after downgrading to tidyverse packages before October 2018.

**Comment by jkuharev** [comment]
Hi George,

I think, I have solved the problem now.
Problem was that tidyr prevented from deleting grouping columns from data frames,
The line "peptides_wide %>% select(-sequence)" failed because sequence was defined as a grouping column. "peptides_wide %>% ungroup() %>% select(-sequence) " seems to work.

I wish Pedro has left more meaningful comments in the FSWE code.

best regards
Jörg

**Comment by grosenberger** [comment]
Great, thanks for your help!
